### ISSUE TITLE
Mautic multiselect values are handled in wrong format

### ISSUE THREAD

**Issue by pety-dc** [verygoodplugins/wp-fusion-lite#11]
The base `format_field_value` implodes the multi/select value arrays into a comma separated string. 

"alpha,beta,gamma"

Mautic multiselect fields however store multiselect values to be separated by "|"-s

"alpha|beta|gamma"

I guess it expects the values in that format too.

**Comment by jack-arturo** [comment]
@pety-dc That change would go in class `WPF_Mautic` in the `format_field_value()` function, something like:

`} elseif ( ( $field_type == 'checkboxes' || $field_type == 'multiselect' ) && ! empty( $value ) ) {

	return str_replace( ',', '|', $value );
`

Can you test it and confirm that works for updating multiselects? I'm not sure we tested that with Mautic yet.

If it works I'll put it into core. Thanks.
