### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by MadBAhmad** [verygoodplugins/wp-fusion-lite#17]
stdClass Object
(
    [data] => Array
        (
            [0] => stdClass Object
                (
                    [code] => INVALID_DATA
                    [details] => stdClass Object
                        (
                            [api_name] => Owner
                        )

                    [message] => invalid data
                    [status] => error
                )

        )

)

What does this mean??

**Comment by jack-arturo** [comment]
@MadBAhmad That looks like you tried to sync an invalid Owner ID value to the "Owner" field.

To update the owner over the API you'd need to sync a valid owner ID, for example 3136853000000150015
