### ISSUE TITLE
Custom CRM only works if the directory name alphabetically follows wp-fusion(-lite)

### ISSUE THREAD

**Issue by pety-dc** [verygoodplugins/wp-fusion-lite#9]
if the directory order is 
```
wp-fusion-lite
wp-fusion-customcrm
```

The `add_filter( 'wpf_crms', 'wpf_custom_crm');` in the custom crm plugin's main php file does not run before wp-fusion's main php file which runs the `apply_fliter` on `wpf_crms`

if the custom crm plugin's directory follows the WP-fusion directory it runs as expected
```
wp-fusion-xxx-customcrm
wp-fusion-lite
```

Either WP-fusion should run the `apply_filter` later, or this naming rule should be highlighted in the Custom CRM developers guide

**Comment by jack-arturo** [comment]
Interesting. I'm not able to reproduce it. I'm not sure why.

In both the full version of WP Fusion and the Lite version, the `wp-fusion-custom-crm` plugin runs its filter in time to include the custom CRM in the list.

What you're saying makes sense regarding the load order. I'm just not sure why it's working properly for me.

I'll put a note on the docs regardless. Thanks.
